name: CD_workflow

on:
  pull_request:
    types:
      - review_requested
    branches:
      - main      #test
      - feature/*
      - develop
      - release/*
      
jobs:
  approve-manual-deployment:
    name: Approve manual deployment
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/github-script@v3
      with:
        script: |
          if (github.event.pull_request.review_comments.some(comment => comment.state === 'approved')) {
            echo 'Deployment approved! Proceeding for it....'
          } else {
            echo 'Deployment not approved! Exiting....'
          }

  CD:
    name: Running CD workflow
    needs: approve-manual-deployment
    uses: adysis14/CICD-stages-node.js-project/.github/workflows/CD_workflow.yml@main
