name: CD_workflow

on:
  pull_request:
    types:
      - closed
  #    - synchronize
    branches:
      - main
      - feature/*
      - develop
      - release/*
      
permissions:
  packages: write
  contents: read
  
jobs:
  CD:
    name: Running CD workflow
    needs: approve-manual-deployment
    uses: adysis14/CICD-stages-node.js-project/.github/workflows/CD_workflow.yml@main
    
  approve-manual-deployment:
    name: Manual Approval for Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: adysis14
        minimum-approvals: 1
        issue-title: "Deploying package"
        issue-body: "Please approve or deny the deployment of Package"
       # exclude-workflow-initiator-as-approver: false
       # additional-approved-words: ''
       # additional-denied-words: ''
      env:
       ISSUE_TOKEN: ${{ secrets.REPO_DISPATCH_ACCESS_TOKEN }}
