name: CI_workflow

on:
  pull_request:
    types:
      - assigned
    branches:
      - main
      - feature/*
      - develop
     # - release/*
      
jobs:
  CI:
    name: Running CI workflow
    uses: adysis14/CICD-stages-node.js-project/.github/workflows/CI_workflow.yml@main

