name: Node.js Package

on:
  push:
    branches:
      - feature/*
      - develop
      - release/*
  pull_request:
    types: [labeled]
  release:

env:
  REPO_ACCESS_TOKEN: ${{ secrets.REPO_DISPATCH_ACCESS_TOKEN }}

jobs:
  
  # CI Job
  build-and-test_CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        run: git checkout master

      - name: Checkout develop
        run: git checkout develop

      - name: Checkout feature
        run: git checkout feature/${{github.event.pull_request.head.ref}}

      - name: Build
        run: |
          npm ci
          echo "Building..."

      - name: Test
        run: |
          echo "Testing..."
          
  merge-feature:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Merge feature branch into develop
      run: |
        git checkout develop
        git merge --ff-only $GITHUB_REF  # Merge the feature branch into develop with a fast-forward-only strategy

    - name: Push changes to develop
      run: |
        git push origin develop
        
  create-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create a release branch
      run: |
        git checkout -b release/v${{ github.run_number }}
        git push origin release/v${{ github.run_number }}
        
  merge-release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Merge release branch into master/main
      run: |
        git checkout main
        git merge --no-ff --no-edit $GITHUB_REF  # Merge the release branch into master, keeping the merge commit

    - name: Push changes to master/main
      run: |
        git push origin main
        
  automerge:
    if: github.event.label.name == 'release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract branch name
      uses: mdecoleman/pr-branch-name@1.0.0
      id: extract_branch
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: yanamura/git-flow-merge-action@v1
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}

  # CD Job
  publish-gpr_CD:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm version major --no-git-tag-version
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }
